// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwBdomPEQ5kKa5B-sTBgCGEWgO9vZ0Ax4',
    appId: '1:12993883815:web:12acd689bb746489b97582',
    messagingSenderId: '12993883815',
    projectId: 'mado-a33a3',
    authDomain: 'mado-a33a3.firebaseapp.com',
    storageBucket: 'mado-a33a3.appspot.com',
    measurementId: 'G-J1DL0MSNV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHr8iqDrwA-kMvd6nzMZuHV3sv-kE2a3A',
    appId: '1:12993883815:android:e556ea517001392db97582',
    messagingSenderId: '12993883815',
    projectId: 'mado-a33a3',
    storageBucket: 'mado-a33a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQMEDfj0r7JY8fNsq9l-UkKiWenm8ai2c',
    appId: '1:12993883815:ios:e54ffe514d406460b97582',
    messagingSenderId: '12993883815',
    projectId: 'mado-a33a3',
    storageBucket: 'mado-a33a3.appspot.com',
    iosClientId: '12993883815-4lo8hb0cfhnasfbc2hf3j5bsnambtd93.apps.googleusercontent.com',
    iosBundleId: 'com.mado.madoapp',
  );
}
